### ISSUE TITLE
plate:nth-child(3); doesn't work for 18?

### ISSUE THREAD

**Issue by Jakobud** [flukeout/css-diner#100]
Seems like the answer is `plate:nth-child(3);`. Doesn't accept it.

**Comment by Moter8** [comment]
It does accept `plate:nth-child(3)`, for some reason it's rejecting it if you include a semicolon.

**Comment by flukeout** [comment]
Selectors don't have semicolons after, but CSS rules do. A more complete rule would look like..

`
plate {
  background: red;
}
`

Notice the semicolon after the CSS rule, but not the selector. Does that clear it up?
