### ISSUE TITLE
Level for Attribute Selectors [] ? 

### ISSUE THREAD

**Issue by frantic1048** [flukeout/css-diner#101]
That would be more interesting with attribute selectors ╮(￣▽￣)╭

- ["attr"="value"]
- ["attr"~="value"]
- ["attr"|="value"]
- ["attr"^="value"]
- ["attr"$="value"]
- ["attr"*="value"]

**Comment by flukeout** [comment]
Yeah, I'll put this on the roadmap. Do you have any ideas for how to present or incorporate it? Here's my idea..

In later levels, some of the plates will have a name associated with the order like "Bob" or "Jane" and users will select the "Bento for Jane" for example. Markup could be `<bento customer="jane"/>` Thoughts?
