### ISSUE TITLE
On Level 19 Of 26  

### ISSUE THREAD

**Issue by mansisce** [flukeout/css-diner#103]
When you try 
bento:first-child instead of bento:nth-last-child(2n) it gives wrong indication. 

Expected behavior is : It should indicate or animate the first bento. As 

Both is correct bento:first-child  and bento:nth-last-child(2n)

**Comment by flukeout** [comment]
`bento:first-child` only selects a bento that is ALSO the first child of a parent element. On level 19, the first bento on the left is the 2nd child element. Does that clear things up?
