### ISSUE TITLE
Suggestion on level 15 (maybe others too)

### ISSUE THREAD

**Issue by Schaferhund** [flukeout/css-diner#105]
In level 15, it is requested selecting the top orange using the first-child pseudo selector, but I think the game should consider the first child the closest one to the parent, so the first child of the plate would be the one touching it.

**Comment by vihanga-liyanage** [comment]
Agree.

**Comment by flukeout** [comment]
Yeah, hearing this over and over so I've added it to the roadmap. Im curious how many people feel this way since only the ones who disagree with how it is are filing issues. Thank you for filing.
