### ISSUE TITLE
#19 correct answer

### ISSUE THREAD

**Issue by iftemplar** [flukeout/css-diner#108]
I'm sorry, but why the correct answer is **bento:nth-last-child(3)**  ?
I thought it must be **bento:nth-last-child(2)**

**Comment by vihanga-liyanage** [comment]
The working answer is <strong>bento:nth-last-child(4)</strong> right? I just checked with the game.

**Comment by GiacomoSorbi** [comment]
I had troubles there too; in the end I passed it with *bento:first-of-type*, but was puzzled by it...

**Comment by 2bmo** [comment]
Can't pass it with bento:nth-last-child(2), div bento:nth-last-child(2), .table bento:nth-last-child(2). Am I get it wrong?

**Comment by manalj** [comment]
Right answer should be `bento:nth-last-child(2)` , instead it passed with `bento:nth-child(2)`

**Comment by TheNuttyMaker** [comment]
The Possible answers are 
bento:nth-last-child(4)   the shaking bento object is at 4th position from last.
bento:nth-child(2) the shaking bento object is at 2nd position from the start
bento:first-of-type  the shaking bento object is first of its type from the start

**Comment by flukeout** [comment]
The correct answer (or one of them) is `bento:nth-last-child(4)`. Take a look below, we're counting the elements from the back, making the bento the 4th element.

![image](https://cloud.githubusercontent.com/assets/25212/17371163/c02ac9de-5953-11e6-8f74-5687a54fbcfe.png)

The `nth` isn't counting every `bento` from the back, it's counting every element. Does that clear things up?

**Comment by yozhikvtumane** [comment]
It should works with `bento:nth-last-child(7)` but doesn't.
http://codepen.io/brinnsergey/pen/eBGGRx

**Comment by yozhikvtumane** [comment]
bento:nth-last-child(4) doesn't work
http://codepen.io/brinnsergey/pen/eBGGRx

**Comment by rvpn** [comment]
correct answer bento:nth-last-child(3) .
