### ISSUE TITLE
nth-child selector

### ISSUE THREAD

**Issue by SamuelMeza** [flukeout/css-diner#109]
Hi there, on Level 18 of 26 ".table plate:nth-child(3)" "div plate:nth-child(3)" are valid selectors but are marked as incorrect, plase verify :)

Great site btw & best regards

**Comment by flukeout** [comment]
You're right, it's a problem with how I'm treating the `.table` part of the selector. All of the rules are already being applied within the `.table` so you don't need to add it...

For example, `plate:nth-child(3)` by itself works just fine. There's another issue that deals with the problem of the `.table` selement - so I'm going to close this for now, thank you for filing!
