### ISSUE TITLE
Level 10 div.table * doesn't work

### ISSUE THREAD

**Issue by AnnaTretyakova** [flukeout/css-diner#110]
On the 10th Level student  is supposed to write just * ,
But div.table * also right but doesn't pass.

**Comment by mak1986** [comment]
True! I also got confused * will mean that the table also will get removed :)

**Comment by HamChao** [comment]
Table suppose to be gone!

**Comment by flukeout** [comment]
I've created a new issue - #117 - for this since a few people have brought it up and I'd like to consolidate it. Cheers!
