### ISSUE TITLE
Syntax div not updating between levels

### ISSUE THREAD

**Issue by Smashman** [flukeout/css-diner#50]
Most notably between level 12, 13 and 14.

See [this gif](http://smash.mn/s/1395700344.gif).

If I select the text in that div, it updates, however.

I'm not sure if this is an issue on your end (I checked everything over and nothing sticks out. It also works in a local version.)

It could be an issue with Chrome in general...

**Comment by flukeout** [comment]
Hmm, I'm unable to reproduce so I'll close for the time being. Are you completing the levels and then not seeing the updates? Is it still an issue? It's been a while haha
