### ISSUE TITLE
Level 13: Please mention having the same parent

### ISSUE THREAD

**Issue by vishalsodani** [flukeout/css-diner#56]
Select every pickle to the right of the bento

I was confused. I thought A ~ B means select every element that follows A. But, it means only those elements which have the same parent as A and the elements follow A.

**Comment by flukeout** [comment]
The help text on the right mentions selecting 'siblings' and also the pickles that are meant to be selected are dancing, so I think between those two clues it should be enough? If you disagree, can you provide an alternative helper text or level title?
