### ISSUE TITLE
Give results at end of test

### ISSUE THREAD

**Issue by i-arindam** [flukeout/css-diner#61]
Give the count of tests taken and passed.
Useful to capture how many were skipped.

Future: Use that info to update the tweet button?

**Comment by flukeout** [comment]
Thanks for filing and also for your PR, which I'll be reviewing shortly. In general, I don't want to keep track of correct vs incorrect guesses - I think that would be good for another mode, like a challenge or test. As is, it's just a fun refresher and I wouldn't want to discourage people from sharing their results if they feel their score is too low.

I will however, use your code & idea to display some sort of Twitter share prompt at the end of the game. I'm going to close this issue as this idea is now reflected in the Roadmap section of the README.md file. Cheers!
