### ISSUE TITLE
Level 17 solution specificity

### ISSUE THREAD

**Issue by kikoval** [flukeout/css-diner#65]
The HTML markup does not enforce to use more specific selectors, espcially the suggested `:last-child`. Correct solution is then simply `apple, pickle`. I suggest to include more of these elements so this trivial solution won't work any more. For instance:

```
<div class="table">
    <plate id="fancy"/>
        <pickle class="small"/>
        <apple class="small"/>
    </plate>
    <plate></plate>
    <plate>
        <orange class="small"/>
        <apple class="small"/>
        <orange/>
    </plate>
    <pickle class="small"/>
    <pickle class="small"/>
</div>
```

**Comment by flukeout** [comment]
I'm going to add these issues to the roadmap on the Readme and close this issue. Thank you for filing.
1. Enforce the use of the level selector
2. Block attampts to use comma between selectors
