### ISSUE TITLE
HTML Viewer not updated when you win

### ISSUE THREAD

**Issue by trondkla** [flukeout/css-diner#66]
When you win, the HTML viewer is not updated. 

If you hold your mouse over the .winner tag (the table) the first plate-tag is highlighted in the HTML viewer.

(Chrome 33 @ Window 8)

Html viewer should be hided or say:
```HTML
<div class="table">
   <span class="winner"><strong>You did it!</strong><br>You are a CSS God.</span>
</div>
```
![css html viewer](https://f.cloud.github.com/assets/464589/2512888/da3dbf32-b42a-11e3-8b3a-62180a63c58e.png)

**Comment by flukeout** [comment]
Fixed and pushed - thank you for filing @trondkla
