### ISSUE TITLE
Level 17: selectors don't work correctly

### ISSUE THREAD

**Issue by tiptronic** [flukeout/css-diner#72]
Should work:
apple .small,pickle .small
#fancy apple, div:last-child
...
should work, but do not

**Comment by thomvil** [comment]
i think maybe `.small:last-child` is better.

**Comment by AndresCuervo** [comment]
This should also work, but doesn't currently: `apple:last-child, div > *:last-child`.

**Comment by flukeout** [comment]
@thomvil has suggested the 'intended' selector here. In general, I will change things so that comma delimited selectors will be discouraged since it's too easy to get around using the rule that the level is trying to demonstrate.

Thank you for filing!
