### ISSUE TITLE
problem with Safari 7.0.2 on Mac in private mode

### ISSUE THREAD

**Issue by manofewords** [flukeout/css-diner#78]
there is a problem with Safari 7.0.2 on Mac in private mode. On level 1, no dancing plates animation, and nothing is displayed in the HTML Viewer. Chrome private mode is ok

**Comment by flukeout** [comment]
Looks like Safari blocks access to localStorage in private mode, which the game relies on, good catch. Safari represents about 6% of users right now, and I'm guessing only a small percentage of those would browse this in private mode, I'm going to leave this open but not prioritize it.

**Comment by flukeout** [comment]
Closin' + thanks for feedback!
