### ISSUE TITLE
HTML code doesn't update on Winning

### ISSUE THREAD

**Issue by tunetosuraj** [flukeout/css-diner#79]
![diner](https://cloud.githubusercontent.com/assets/723253/2552454/8eae87c4-b699-11e3-98fa-8c47b48fe2be.jpg)
The code should be updated on completing level 26. When you hover on the table, it highlights the element and the code. As seen on the screenshot above.

**Comment by flukeout** [comment]
I've fixed this issue - on the winner screen the code no longer highlights!

I agree about social sharing, work is already underway to add a social sharing prompt when you complete the last level. Cheers!
