### ISSUE TITLE
Level 10: Answer * is technically incorrect (scoping issue)

### ISSUE THREAD

**Issue by vekelly09** [flukeout/css-diner#83]
Similar to the last comment left, but in this case the answer accepted is actually wrong.  It is just a matter that, as you say, all your selectors are implicitly scoped inside the <table> for teaching purposes, but  they would not be for real CSS code in the wild.  In other cases, that just causes the site to miss some correct answers, but here it actually accepts an incorrect one: "*" instead of "div *" or ".table *".  (I would love to assign your site to my students for CSS practice; excellent reinforcement!)

**Comment by flukeout** [comment]
Thanks for filing, I've created a new master issue to track this (#117) as it's come up for many users. Closing to continue work there.
