### ISSUE TITLE
Level 19 - Cannot find one valid selector according to the page

### ISSUE THREAD

**Issue by rainabba** [flukeout/css-diner#87]
I found at least 3 valid selectors that fit the criteria but none worked even though many would "shake" the intended element visual.

Finally found that bento:nth-child(2) did work. The page was emphasizing :nth-last-child

According to https://github.com/flukeout/restaurant/blob/master/levels.js, the intended target was: bento:nth-last-child(4) but what finally worked (as I was testing to list for this issue) was bento:nth-child(2)

This demo is only supposed to succeed on a single, specific selector, not "valid selectors"?

"Select the 1st bento"

<div class="table">
<plate></plate>
<bento></bento>
<apple class="small"/>
<plate>
<orange/>
<orange/>
<orange/>
</plate>
<bento></bento>
</div>

Tried:
div > bento:first-of-type
div > bento:nth-child(2)
div > bento:nth-last-child(4)
bento:nth-child(2) (finally worked)

**Comment by mdan312** [comment]
Yes it is the `DIV.table` that does not work. Same for level 18

**Comment by flukeout** [comment]
Thanks for the discussion, it hits on a few issues that I've addressed in the roadmap
- I need to enforce a single level-specific selector for each level
- `bento:nth-last-child(4)` is correct and the 'intended' answer
  - I will add some hints or helpers on this level
- I need to resolve how I handle  `.table` within the selector, currently it breaks things when it really shouldn't

Thanks everyone, closing as these are reflected in the roadmap on the readme.

**Comment by NatashaSilva** [comment]
5 years later .... 
bento:nth-last-child(4)  is not working anymore. I tried this one and I could get using it.  
These two are working: 
bento:first-of-type
bento:nth-child(2)

**Comment by ankit15597** [comment]
> 5 years later ....
> bento:nth-last-child(4) is not working anymore. I tried this one and I could get using it.
> These two are working:
> bento:first-of-type
> bento:nth-child(2)

Ideally, bento:nth-child(1) should be working.
The :nth-child(n) selector matches every element that is the nth child, regardless of type, of its parent.
In this case, The 1st bento has to be selected which is a child of div.

**Comment by dimasupostat** [comment]
100% works
bento:nth-last-child(3)
