### ISSUE TITLE
level 1: hint if you don't get what game is expecting you to do?

### ISSUE THREAD

**Issue by minzgeprahl** [flukeout/css-diner#88]
hi, 
first of all, thanks for creating this game! as a total beginner in html/css, i must admit it took me several minutes to understand what i was expected to enter. i tried 'real' types first, like <p> and <ul> and it took me a while to understand i should enter 'plate' , without the < > . 
i understand that at the moment there is no 'feedback' feature included in the game, like error messages appearing when you fail to do something. even if there is no way to do this, maybe the explanations for level 1 could be modified so it's easier to grasp the concept of the game quickly.

**Comment by Luomint** [comment]
This should be fixed, very counter intuitive at first

**Comment by markrjr** [comment]
The "Selects all elements of type A." makes it sound like you want the user to type as the element. Just put "plate."

**Comment by flukeout** [comment]
@minzgeprahl There is a 'help i'm stuck' link on the first level and it shows the following content...

![image](https://cloud.githubusercontent.com/assets/25212/17371955/c78f4382-5956-11e6-8478-55e1157230ec.png)

Would this content have helped you if you saw it? Maybe the help link isn't prominent enough? Let me know - closing this issue but please file a follow up if you think the copy in the help text in not helpful.
