### ISSUE TITLE
Extra advice for level 6

### ISSUE THREAD

**Issue by chaoaretasty** [flukeout/css-diner#90]
I like this for introducing people to CSS selectors but I've noticed something that trips a few people up on level 6.

`plate.small` is a quite obvious solution and does do what the question is asking yet people get stuck rather than just trying to use `.small`. I think either allow both answers on this one or perhaps a short note on the right where the selector is introduced to recommend using just class names rather than element.class.

**Comment by leesei** [comment]
Level 6 I see accepts `apple.small` and `.small` as answer.
Perhaps this can be closed?

**Comment by flukeout** [comment]
`plate.small` is not a valid answer for level 6, that would `<plate class="small">`.

@leesei is right, both `apple.small` and `.small` are valid, so I'm going to close this issue.
