### ISSUE TITLE
Hamburger menu (with level seletor) should close on selecting level

### ISSUE THREAD

**Issue by VeldMuijz** [flukeout/css-diner#92]
This game is great fun, I like the graphics they are well made :+1: Thanks for making it!

I had one remark on the UX though, when opening up the level selecting menu and clicking on a level I would expect to see the level selector close automatically, I had to close it by hand..

Before selecting a level:
![image](https://cloud.githubusercontent.com/assets/1394439/3590397/9796bd2e-0c58-11e4-9742-eb1eade29c89.png)

After selecting a level:
![image](https://cloud.githubusercontent.com/assets/1394439/3590415/d19030dc-0c58-11e4-91a9-4a07886e056a.png)

The level selecting menu will block the user help/description for that level. Maybe you could make it close after selecting a level or clicking elsewhere on the page.

**Comment by flukeout** [comment]
That's a good idea! In general the UX of changing between levels sucks - it's hard to tell what level number you are on, and it's not easy to navigate between levels.

**Comment by flukeout** [comment]
Fixed - thanks for filing!
